### ISSUE TITLE
Browse datasheets

### ISSUE THREAD

**Issue by WouterThys** [WouterThys/InventoryApp#4]
Browse datasheet in edit item dialog -> under local datasheet the "browse" button misses

**Comment by WouterThys** [comment]
wait for it

**Comment by VincentDeHaen** [comment]
ok @WouterThys

**Comment by WouterThys** [comment]
![image](https://user-images.githubusercontent.com/4941694/31251772-6e78a1f6-aa1f-11e7-89ce-36e0ea7c0554.png)

**Comment by VincentDeHaen** [comment]
hi wally i created a pull request 
#18

**Comment by VincentDeHaen** [comment]
good job waldo
